use std::error::Error;

pub async fn configure() -> Result<(), Box<dyn Error>> {
    Ok(())
}
